version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - echo "setting permission permissions"
      - chmod +x build-image.sh push-image.sh
      - ./build-image.sh

  build:
    commands:
      - ./push-image.sh